name: trunk

on:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [14.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable
      - run: yarn build
      - run: yarn test

  # https://github.community/t/how-can-i-test-if-secrets-are-available-in-an-action/17911/10
  checkNpmTokenSet:
    name: Check if NPM_TOKEN secret is set
    runs-on: ubuntu-latest
    outputs:
      isNpmTokenSet: ${{ steps.checkNpmTokenSet.outputs.is_MY_SECRET_set }}
    steps:
      - name: Check if NPM_TOKEN secret is set
        id: checkNpmTokenSet
        run: |
          echo "isNpmTokenSet: ${{ secrets.NPM_TOKEN != '' }}"
          echo "::set-output name=isNpmTokenSet::${{ secrets.NPM_TOKEN != '' }}"

  release-canary-1:
    needs: [checkNpmTokenSet]
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{needs.checkNpmTokenSet.outputs.isNpmTokenSet}}'

  release-canary:
    needs: [checkNpmTokenSet]
    if: needs.checkNpmTokenSet.outputs.isNpmTokenSet == true
    uses: prisma-labs/dripip/.github/workflows/release.yml@master
    secrets:
      npmToken: ${{secrets.NPM_TOKEN}}
      githubToken: ${{secrets.GITHUB_TOKEN}}
